name: simple-media-converter

services:
  bot:
    build: .
    env_file: .env
    depends_on: [telegram-bot-api]
    environment:
      BOT_API_URL: http://telegram-bot-api:8081
    volumes:
      - api-data:/var/lib/telegram-bot-api

  telegram-bot-api:
    image: aiogram/telegram-bot-api:9.0
    env_file: .env
    volumes:
      - api-data:/var/lib/telegram-bot-api

volumes:
  api-data:
