name: 🚀 Build & Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions: write-all
jobs:
  docker-push:
    name: 🐳 Build and push Docker image
    runs-on: ubuntu-24.04
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
    steps:
      - name: 🔑 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏷️ Prepare Docker tag
        run: echo "DOCKER_TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV # Remove leading v

      - name: 📥 Check out repository code
        uses: actions/checkout@v4

      - name: 🏗️ Build Docker image
        run: docker build --tag $IMAGE:$DOCKER_TAG --tag $IMAGE:latest .

      - name: 📤 Push Docker image
        run: docker push $IMAGE --all-tags
